name: static-scan
on:
  schedule:
      - cron: '*/20 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: action/checkout@v3
      
      - name: Create zip archive
        run: zip -r ./veracode.zip ./target/verademo.war
          
      - name: Pipeline scan
        uses: veracode/Veracode-pipeline-scan-action@fe0924c134a03ab5a74fcb9722ed8456efa48e17 # v1.0.16
        with:
          vid: "vera01ei-1150d22d212a6b98f53723a8cc30c8b7"
          vkey: "vera01es-4aced5543138c63c5cd765fe4425296e832da1e3a1bedcbb08bd2cc0f1bbd2ffe0fa7f9fb110577a1ea8e3f6efc0cc26557e0fb0a01a61f6149bbefe275ba4a3"
          file: "./veracode.zip"
          fail_on_severity: "'Very High','High'"
          timeout: 60
          verbose: true
