# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Sarif Testing

on: push

jobs:
 get-policy-flaws:
   runs-on: ubuntu-latest
   steps:
     - name: checkout repo
       uses: actions/checkout@v3
       
     - name: get policy flaws
       run: |
         ls -lrt .
         cp response.json /tmp/policy_flaws.json

     - name: save results file
       uses: actions/upload-artifact@v3
       with:
         name: policy-flaws
         path: /tmp/policy_flaws.json


 results_to_sarif:
   runs-on: ubuntu-latest
   needs: get-policy-flaws
   name: convert policy results to sarif
   steps:
     - name: Get scan results
       uses: actions/download-artifact@v3
       with:
         name: "policy-flaws"
  
     - name: Convert policy scan output to SARIF format
       id: convert
       uses: Veracode/veracode-pipeline-scan-results-to-sarif@v2.0.4
       with:
         results-json: policy_flaws.json
         scan-type: policy
         output-results-sarif: veracode-results.sarif
         repo_owner: sroy037
         repo_name: verademo-java-web
         commitSHA: 3b5572a5975d4233c334aa8da731f8b3e7ea903a
         ref: refs/heads/main
         githubToken: ${{ secrets.token }}

     - name: save sarif file
       uses: actions/upload-artifact@v3
       with:
         name: sarif-file
         path: veracode-results.sarif

 upload-sarif:
   runs-on: ubuntu-latest
   needs: results_to_sarif
   name: upload sarif
   steps:
     - name: Checkout Repo
       uses: actions/checkout@v3
       with:
         repository: verademo-java-web

     - name: Get scan results
       uses: actions/download-artifact@v3
       with:
         name: "sarif-file"

     - name: Upload SARIF file
       uses: github/codeql-action/upload-sarif@v3
       with:
         sarif_file: veracode-results.sarif
